# Generated by Django 3.1.2 on 2020-10-10 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Рассказ', 'verbose_name_plural': 'Рассказы'},
        ),
        migrations.AddField(
            model_name='post',
            name='tpublish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Текст рассказа'),
        ),
    ]
