# Generated by Django 3.1.2 on 2020-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201022_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=300, verbose_name='Автор, название книги и главы'),
        ),
    ]
